version: '3.9'

networks:
  tree:
    name: tree
    driver: bridge

services:
  mongo: 
    image: 'mongo:latest'
    container_name: 'mongo'
    networks:
      - tree
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017

  redis: 
    image: 'redis:latest'
    container_name: 'redis'
    environment:
      - REDIS_PASSWORD=root
    ports:
      - 6379:6379
    networks:
      - tree

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_BASICAUTH=false
    networks:
      - tree
    depends_on:
      - mongo

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    networks:
      - tree
    depends_on:
      - redis